using DVSRegister.BusinessLogic.Models;
using DVSRegister.BusinessLogic.Models.CAB;
using DVSRegister.BusinessLogic.Services.TestData;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace DVSRegister.Controllers
{

    /// <summary>
    /// For creating test providers and services.
    ///Click toggle button in footer to see test data buttons
    /// </summary>
    /// <param name="environment"></param>
    /// <param name="testDataService"></param>
    /// <param name="logger"></param>
    [Route("cab-service-test-data")]
    public class TestDataController(IWebHostEnvironment environment, ITestDataService testDataService, ILogger<TestDataController> logger) : BaseController(logger)
    {
        private readonly IWebHostEnvironment environment = environment;
        private readonly ITestDataService testDataService = testDataService;


        /// <summary>
        ///Seed data from TestData folder
        ///Secondary contact email will be generated by adding +reviewer, and should be added in notify
        ///to receive secondary contact emails
        /// </summary>
        /// <returns></returns>
        /// <exception cref="InvalidOperationException"></exception>

        [HttpPost("provider-test-data")]
        public async Task<IActionResult> CreateTestProvider()
        {
            if (!IsValidCabId(CabId))
                return HandleInvalidCabId(CabId);

            bool allowTestDataCreation;
            if(environment.IsDevelopment() || environment.IsStaging())
            {
                allowTestDataCreation = true;
            }

            else
            {               
                throw new InvalidOperationException("Test data creation not allowed in production");
            }

            var providerDataPath = Path.Combine( environment.ContentRootPath, "TestData", "provider-seed.json");
            ProviderProfileDto? providerProfileDto = new();
            using (StreamReader r = new StreamReader(providerDataPath))
            {
                string json = r.ReadToEnd();
                providerProfileDto = JsonSerializer.Deserialize<ProviderProfileDto>(json);
            }

         
            await testDataService.CreateTestProvider(UserEmail, allowTestDataCreation, providerProfileDto!);
            return RedirectToAction("AllProviders", "Home");

        }

        /// <summary>
        /// Fetch and seed data from json in TestData folder
        /// For new service tf versions add additional json files
        /// Json can be created by adding code to serialize ServiceDto as json, 
        /// run the application to create service and capture json in CabService.cs before saving it
        /// </summary>
        /// <param name="providerId"></param>
        /// <param name="version"></param>
        /// <returns></returns>
        /// <exception cref="InvalidOperationException"></exception>

        [HttpPost("services-test-data")]
        public async Task<IActionResult> CreateTestServices(int providerId, string version)
        {
            if (!IsValidCabId(CabId))
                return HandleInvalidCabId(CabId);
            bool allowTestDataCreation;
            if (environment.IsDevelopment() || environment.IsStaging())
            {
                allowTestDataCreation = true;
            }

            else
            {
                throw new InvalidOperationException("Test data creation not allowed in production");
            }

            string fileName = $"{version}-service-seed.json";
          

            var path = Path.Combine(environment.ContentRootPath, "TestData", fileName);
            List<ServiceDto>? services = new();
            using (StreamReader r = new StreamReader(path))
            {
                string json = r.ReadToEnd();
                var seed = JsonSerializer.Deserialize<ServicesSeedDto>(json,
                new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

                services = seed!.Services;
            }
            await testDataService.CreateTestServices(UserEmail, allowTestDataCreation, providerId,services);
            return Redirect( Url.Action( "ProviderDetails","CabProvider",new { providerId = providerId }) + "#services"
            );

        }


        /// <summary>
        /// Sets TestDataEnabled bool value, based on which view or hide test data buttons
        /// </summary>
        /// <returns></returns>
        /// <exception cref="InvalidOperationException"></exception>

        [HttpPost("toggle")]
        public IActionResult Toggle()
        {

            if (!environment.IsDevelopment() && !environment.IsStaging())
                throw new InvalidOperationException("Test data enable not allowed in production");

            bool isEnabled = TempData["TestDataEnabled"] as bool? ?? false;

            // Always toggle
            TempData["TestDataEnabled"] = !isEnabled;
            TempData.Keep("TestDataEnabled");

            var returnUrl = Request.Headers["Referer"].ToString();
            if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("AllProviders", "Home");


        }

    }
}
